CREATE TABLE IF NOT EXISTS checks (
    id SERIAL PRIMARY KEY,
    doc_id VARCHAR(50) NOT NULL,
    item VARCHAR(200) NOT NULL,
    category VARCHAR(100) NOT NULL,
    amount INT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    discount NUMERIC(10, 2) NOT NULL DEFAULT 0
);